<?php

 $title = utf8_encode('Neue Buchung hinzufügen');
 $this->headTitle($title);
 ?>
 <p>
    <?php if ($errorMessage) {
		echo '<font color="red">Es ist ein Fehler aufgetreten: </font>' . $this->escapeHtml($errorMessage);
	}?>
</p>
<p>
    <?php if ($successMessage) {
		echo '<font color="green">' . $this->escapeHtml($errorMessage) . '</font>';
	}?>
</p>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('booking', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 #echo $this->formHidden($userTimeModelForeignKey);
 echo $this->formRow($form->get('timeStamp'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('text'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 