<?php
$title = 'Ihre Buchungen';
$this->headTitle($title);
?>
<br />
<a href="<?php echo $this->url('booking',
            array('action'=>'booking'));?>"></a>
<p>
    <?php echo '<strong>Eingeloggt als Benutzer: </strong>' . $this->escapeHtml($userName);?>
    <a href="<?php echo $this->url('logout',
            array('action'=>'logout'));?>">&nbsp;Logout</a>
    <?php echo ' | <strong>Saldo: </strong>' . $this->escapeHtml($timeBalance);?>
    <?php echo ' | <strong>Personalnummer: </strong>' . $this->escapeHtml($staffNumber);?>
</p>
<p>
    <?php if ($errorMessage) {
		echo '<font color="red">Es ist ein Fehler aufgetreten: </font>' . $this->escapeHtml($errorMessage);
	}?>
</p>
<p>
    <?php if ($successMessage) {
		echo '<font color="green">' . $successMessage . '</font>';
	}?>
</p>
<h1><?php echo $this->escapeHtml($title);?></h1>

<p>
    <a href="<?php echo $this->url('booking', array('action'=>'add'));?>">Neue Buchung hinzufügen</a>
</p>

<table class="table">
<tr>
    <th>Buchungsnummer</th>
    <th>Datum/Uhrzeit</th>
    <th>Typ</th>
    <th>Beschreibung</th>
    <th>Benutzer-ID</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($bookings as $booking) : ?>
<tr>
    <td><?php echo $this->escapeHtml($booking->primaryKey);?></td>
    <td><?php echo $this->escapeHtml($booking->timeStamp);?></td>
    <td><?php echo $this->escapeHtml($booking->type);?></td>
    <td><?php echo $this->escapeHtml($booking->text);?></td>
    <td><?php echo $this->escapeHtml($booking->userForeignKey);?></td>
    <td>
        <a href="<?php echo $this->url('booking',
            array('action'=>'edit', 'id' => $booking->primaryKey));?>">Bearbeiten&nbsp;</a>
        <a href="<?php echo $this->url('booking',
            array('action'=>'delete', 'id' => $booking->primaryKey));?>">Löschen</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
