<?php
$title = 'Ihre Buchungen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
    <?php echo '<strong>Eingeloggt als Benutzer: </strong>' . $this->escapeHtml($userName);?>
	<a href="<?php echo $this->url('logout',
            array('action'=>'logout'));?>">&nbsp;&nbsp;Logout</a>
<p>
    <?php echo $this->escapeHtml($errorMessage);?>
</p>
<p>
    <a href="<?php echo $this->url('booking', array('action'=>'add'));?>">Neue Buchung hinzufügen</a>
</p>

<table class="table">
<tr>
    <th>Buchungsnummer</th>
    <th>Zeit</th>
    <th>Typ</th>
    <th>Beschreibung</th>
    <th>Benutzerkennung</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($bookings as $booking) : ?>
<tr>
    <td><?php echo $this->escapeHtml($booking->primaryKey);?></td>
    <td><?php echo $this->escapeHtml($booking->timeStamp);?></td>
    <td><?php echo $this->escapeHtml($booking->type);?></td>
    <td><?php echo $this->escapeHtml($booking->text);?></td>
    <td><?php echo $this->escapeHtml($booking->userForeignKey);?></td>
    <td>
        <a href="<?php echo $this->url('booking',
            array('action'=>'edit', 'pk' => $booking->primaryKey));?>">Bearbeiten</a>
        <a href="<?php echo $this->url('booking',
            array('action'=>'delete', 'pk' => $booking->primaryKey));?>">Anzeigen</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
