<?php

 utf8_encode('Buchung löschen');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Wollen Sie diese Buchung löschen
     '<?php echo $this->escapeHtml($booking->timeStamp); ?>' by
     '<?php echo $this->escapeHtml($booking->text); ?>'?
 </p>
 <?php
 $url = $this->url('booking', array(
     'action' => 'delete',
     'pk'     => $this->primaryKey,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $booking->primaryKey; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>