<?php

 $title = utf8_encode('Buchung bearbeiten');
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'booking',
     array(
         'action' => 'edit',
         'id'     => $this->primaryKey,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('timeStamp'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('text'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 