<?php
 $title = utf8_encode('Buchung bearbeiten');
 $this->headTitle($title);
 ?>
 <a href="<?php echo $this->url('booking',
            array('action'=>'booking'));?>">Ihre Buchungen</a>
 <a href="<?php echo $this->serverUrl(true);?>"><?php echo $this->escapeHtml($title); ?></a>
 <p>
    <?php if ($errorMessage) {
		echo '<font color="red">Es ist ein Fehler aufgetreten: </font>' . $this->escapeHtml($errorMessage);
	}?>
</p>
<p>
    <?php if ($successMessage) {
		echo '<font color="green">' . $this->escapeHtml($errorMessage) . '</font>';
	}?>
</p>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'booking',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('timeStamp'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('text'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 