<?php
 $title = utf8_encode('Buchung bearbeiten');
 $this->headTitle($title);
 ?>
 <a href="<?php echo $this->url('booking',
            array('action'=>'booking'));?>">Ihre Buchungen&nbsp;|</a>
 <a href="<?php echo $this->serverUrl(true);?>"><?php echo $this->escapeHtml($title); ?></a>
 <p>
    <?php if ($errorMessage) {
		echo '<font color="red">Es ist ein Fehler aufgetreten: </font>' . $this->escapeHtml($errorMessage);
	}?>
</p>
<p>
    <?php if ($successMessage) {
		echo '<font color="green">' . $this->escapeHtml($errorMessage) . '</font>';
	}?>
</p>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'booking',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('timeStamp'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('text'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 <br />
 <p>
    <h4>Hinweise zu Eingabe</h4>
    <ul>
        <li><strong>Datum/Uhrzeit:&nbsp;</strong>Das g&uuml;ltige Format ist "TT.MM.JJJJ HH:MM", also zum Beispiel "01.01.2015 08:00".</li>
        <li><strong>Buchungstyp:&nbsp;</strong>Der Typ ist aus dem Dropdown-Feld auszuw&auml;hlen.* </li>
        <li><strong>Buchungstext:&nbsp;</strong>Freitextfeld mit maximal 100 Zeichen.</li>
    </ul>
* <em>Bei der Auswahl von "U" oder "UH" f&uuml;r eine Urlaubsbuchung ist lediglich das Datum relevant, nicht jedoch die Uhrzeit.<br />
&nbsp;&nbsp;Eine eingegebene Uhrzeit wird vom System automatisch entfernt und dann eine Urlaubsbuchung gem&auml;&szlig; der<br /> 
&nbsp;&nbsp;Soll-Arbeitszeit berechnet.</em>
</p>
