<?php
$title = 'My bookings';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
    <a href="<?php echo $this->url('booking', array('action'=>'add'));?>">Add new booking</a>
</p>

<table class="table">
<tr>
    <th>Booking ID</th>
    <th>Time stamp</th>
    <th>Type</th>
    <th>Text</th>
    <th>User ID</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($bookings as $booking) : ?>
<tr>
    <td><?php echo $this->escapeHtml($booking->primaryKey);?></td>
    <td><?php echo $this->escapeHtml($booking->timeStamp);?></td>
    <td><?php echo $this->escapeHtml($booking->type);?></td>
    <td><?php echo $this->escapeHtml($booking->text);?></td>
    <td><?php echo $this->escapeHtml($booking->userForeignKey);?></td>
    <td>
        <a href="<?php echo $this->url('booking',
            array('action'=>'edit', 'pk' => $booking->primaryKey));?>">Edit</a>
        <a href="<?php echo $this->url('booking',
            array('action'=>'delete', 'pk' => $booking->primaryKey));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
