<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'login',
     array(
         'action' => 'login',
         'userName'     => $this->userName,
         'passWord'     => $this->passWord,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('userName'));
 echo $this->formRow($form->get('passWord'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 